name: core_ui
description: Shared UI, providing reusable widgets, themes, and localization helpers.
repository: https://github.com/flutter-news-app-full-source-code/core-ui
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: 28c7a57b5ce05e23ff70b953e067e3643368aea6
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
